<?php
session_start();
require_once 'config.php';
require_once 'ml_recommendations.php';
require('fpdf.php');

if (!isset($_SESSION['user_id']) || ($_SESSION['user_role'] ?? '') !== 'admin') {
    header("Location: index.php");
    exit();
}

ensureTrainingRecommendationsTable($con);

// Same aggregation as training_needs_summary.php (the on-screen version) -
// kept as a plain duplicate query rather than a shared function, matching
// this codebase's existing convention of each *_pdf.php being self-contained
// (see Individual_Development_Plan_pdf.php, generate_summary.php).
$candidatesStmt = $con->query("
    SELECT d.id, d.title, d.training_type, d.pipeline_status, u.department
    FROM training_demand d
    JOIN training_recommendations tr ON tr.demand_id = d.id
    JOIN users u ON u.id = tr.user_id
    WHERE tr.status IN ('Accepted', 'Training Available', 'Confirmed', 'Completed')
");
$candidates = $candidatesStmt ? $candidatesStmt->fetch_all(MYSQLI_ASSOC) : [];

$demandSummary = [];
foreach ($candidates as $row) {
    $id = $row['id'];
    if (!isset($demandSummary[$id])) {
        $demandSummary[$id] = [
            'title' => $row['title'],
            'training_type' => $row['training_type'],
            'pipeline_status' => $row['pipeline_status'],
            'college_counts' => [],
        ];
    }
    $code = canonicalTnaCollegeCode($row['department']) ?? 'Other';
    $demandSummary[$id]['college_counts'][$code] = ($demandSummary[$id]['college_counts'][$code] ?? 0) + 1;
}
foreach ($demandSummary as &$d) {
    $d['total'] = array_sum($d['college_counts']);
    $parts = [];
    foreach ($d['college_counts'] as $code => $count) {
        $parts[] = "$code ($count)";
    }
    $d['breakdown'] = implode(', ', $parts);
}
unset($d);
uasort($demandSummary, fn($a, $b) => $b['total'] <=> $a['total']);
$demandSummary = array_values($demandSummary);

class PDF extends FPDF
{
    function Header() {
        $this->Image('images/lspu-logo.png', 15, 8, 20);
        $this->SetFont('Arial', 'B', 11);
        $this->Cell(0, 5, 'Republic of the Philippines', 0, 1, 'C');
        $this->SetFont('Arial', 'B', 13);
        $this->Cell(0, 6, 'Laguna State Polytechnic University', 0, 1, 'C');
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 5, 'Province of Laguna', 0, 1, 'C');
        $this->Ln(4);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 8, 'TRAINING NEEDS SUMMARY', 0, 1, 'C');
        $this->SetFont('Arial', '', 8);
        $this->Cell(0, 4, 'Generated by TrainWise on ' . date('F j, Y'), 0, 1, 'C');
        $this->Ln(4);
    }

    function Footer() {
        $this->SetY(-12);
        $this->SetFont('Arial', '', 7);
        $this->Cell(0, 4, 'Generated automatically by TrainWise - reflects live data as of ' . date('F j, Y g:i A'), 0, 0, 'C');
    }
}

$pdf = new PDF();
$pdf->AddPage();

$colWidths = [90, 20, 15, 45, 20]; // Training, Type, Reqs, Requested By, Status short code

$pdf->SetFont('Arial', 'B', 8);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell($colWidths[0], 7, 'Training', 1, 0, 'L', true);
$pdf->Cell($colWidths[1], 7, 'Type', 1, 0, 'L', true);
$pdf->Cell($colWidths[2], 7, 'Reqs', 1, 0, 'C', true);
$pdf->Cell($colWidths[3], 7, 'Requested By', 1, 0, 'L', true);
$pdf->Cell($colWidths[4], 7, 'Status', 1, 1, 'L', true);

$pdf->SetFont('Arial', '', 7);
$statusShort = [
    'Pending HR Review' => 'Pending',
    'Forwarded to Dean' => 'Forwarded',
    'Training Found'    => 'Found',
    'HR Approved'       => 'Approved',
    'Confirmed'         => 'Confirmed',
    'Training Completed' => 'Completed',
    'Closed'            => 'Closed',
];

if (empty($demandSummary)) {
    $pdf->Cell(array_sum($colWidths), 8, 'No training has been requested by any employee yet.', 1, 1, 'C');
} else {
    foreach ($demandSummary as $d) {
        $title = substr($d['title'], 0, 58);
        // 2026-09-09 fix - 'Training' as a fallback asserted a fictional
        // detail nobody has confirmed yet (see training_pipeline.php's "To
        // be determined" and the matching fix across the dean dashboards).
        // "TBD" instead of the full phrase since this column is only 13
        // chars wide (same short-label convention as $statusShort above).
        $type = substr($d['training_type'] ?? 'TBD', 0, 13);
        $breakdown = substr($d['breakdown'], 0, 34);
        $status = $statusShort[$d['pipeline_status']] ?? $d['pipeline_status'];

        $pdf->Cell($colWidths[0], 6, $title, 1);
        $pdf->Cell($colWidths[1], 6, $type, 1);
        $pdf->Cell($colWidths[2], 6, (string)$d['total'], 1, 0, 'C');
        $pdf->Cell($colWidths[3], 6, $breakdown, 1);
        $pdf->Cell($colWidths[4], 6, $status, 1);
        $pdf->Ln();
    }
}

$pdf->Output();
